import ConZF.Repl
/-
Canonical assignments from a local rule (doc/main.tex, Lemma 4.2). A rule `r η l ξ` says that the
child with label `l` of a node with target `η` has target `ξ`. The assignment `Tr r η` is
defined from it by recursion on the path, so coherence reduces to conditions at one node.
-/
universe u

namespace PSet

theorem Label.Equiv.refl : (l : Label.{u}) → l.Equiv l
  | .a => .a
  | .b w => .b (PSet.Equiv.refl w)
  | .c x => .c (PSet.Equiv.refl x)

variable {D : PSet.{u} → PSet.{u}} {U : PSet.{u}}

/-- The assignment generated by a rule, with root target `η`. -/
inductive Tr (r : PSet.{u} → Label.{u} → PSet.{u} → Prop) (η : PSet.{u}) :
    Path.{u} → PSet.{u} → Prop
  | nil {t} : η ≈ t → Tr r η [] t
  | cons {p t l ξ} : Tr r η p t → r t l ξ → Tr r η (l :: p) ξ

/-- The conditions on a rule, relative to a class `C` of targets. -/
structure Rule (D : PSet.{u} → PSet.{u}) (U : PSet.{u})
    (r : PSet.{u} → Label.{u} → PSet.{u} → Prop) (C : PSet.{u} → Prop) : Prop where
  func : ∀ {η l ξ ξ'}, r η l ξ → r η l ξ' → ξ ≈ ξ'
  resp : ∀ {η η' : PSet.{u}} {l l' : Label.{u}} {ξ ξ' : PSet.{u}},
    η ≈ η' → l.Equiv l' → ξ ≈ ξ' → r η l ξ → r η' l' ξ'
  C_resp : ∀ {η η' : PSet.{u}}, η ≈ η' → C η → C η'
  /-- children have targets that are elements, and stay in the class -/
  mem : ∀ {η l ξ}, C η → r η l ξ → ξ ∈ η ∧ C ξ
  /-- a target is the union of the successors of the targets of the available children -/
  sup : ∀ {η G}, C η → (∀ x, x ∈ G ↔ ¬¬∃ ζ, r η .a ζ ∧ x ∈ ζ) →
    ∀ x, x ∈ η ↔ ¬¬∃ l ξ, Avail D U G l ∧ r η l ξ ∧ x ∈ succ ξ

namespace Rule
variable {r : PSet.{u} → Label.{u} → PSet.{u} → Prop} {C : PSet.{u} → Prop}
  (hr : Rule D U r C)
include hr

theorem tr_func {η p t t'} (h : Tr r η p t) (h' : Tr r η p t') : t ≈ t' := by
  induction h generalizing t' with
  | nil e => cases h' with | nil e' => exact e.symm.trans e'
  | cons _ h1 ih =>
    cases h' with
    | cons h0' h1' =>
      exact hr.func h1 (hr.resp (ih h0').symm (Label.Equiv.refl _) (Equiv.refl _) h1')

theorem tr_C {η p t} (hη : C η) (h : Tr r η p t) : C t := by
  induction h with
  | nil e => exact hr.C_resp e hη
  | cons _ h1 ih => exact (hr.mem ih h1).2

theorem tr_cons_iff {η p t l ξ} (h : Tr r η p t) : Tr r η (l :: p) ξ ↔ r t l ξ :=
  ⟨fun h' => by
    cases h' with
    | cons h0 h1 =>
      exact hr.resp (hr.tr_func h0 h) (Label.Equiv.refl _) (Equiv.refl _) h1,
   fun h' => .cons h h'⟩

omit hr in
theorem tr_resp_root {η η' p t} (e : η ≈ η') (h : Tr r η p t) : Tr r η' p t := by
  induction h with
  | nil e' => exact .nil (e.symm.trans e')
  | cons _ h1 ih => exact .cons ih h1

theorem coherent {η} (hη : C η) : Coherent D U (Tr r η) ∧ Tr r η [] η := by
  refine ⟨⟨?_, ?_, ?_, ?_, ?_⟩, .nil (Equiv.refl _)⟩
  · intro p t t' h e
    cases h with
    | nil e' => exact .nil (e'.trans e)
    | cons h0 h1 => exact .cons h0 (hr.resp (Equiv.refl _) (Label.Equiv.refl _) e h1)
  · exact fun h h' => hr.tr_func h h'
  · intro l l' p t e h
    cases h with
    | cons h0 h1 => exact .cons h0 (hr.resp (Equiv.refl _) e (Equiv.refl _) h1)
  · intro l p t t' h h'
    cases h with
    | cons h0 h1 =>
      exact (mem_congr_right (hr.tr_func h0 h')).1 (hr.mem (hr.tr_C hη h0) h1).1
  · intro p t G h hG x
    refine (hr.sup (hr.tr_C hη h) (fun y => (hG y).trans <| nn_congr <| exists_congr fun ζ =>
      and_congr (hr.tr_cons_iff h) Iff.rfl) x).trans ?_
    exact nn_congr <| exists_congr fun l => exists_congr fun ξ => and_congr Iff.rfl <|
      and_congr (hr.tr_cons_iff h).symm Iff.rfl

/-- Replacement for functional relations whose values are in the class of a rule, provided the
root of the glued tree is not not accessible. -/
theorem replacement (s : PSet.{u}) (hU : U = s) (φ : PSet.{u} → PSet.{u} → Prop)
    (φ_resp : ∀ {x x' y y'}, x ≈ x' → y ≈ y' → φ x y → φ x' y')
    (φ_func : ∀ {x y y'}, x ∈ s → φ x y → φ x y' → y ≈ y')
    (φ_C : ∀ {x y}, x ∈ s → φ x y → C y)
    (hacc : SWF (Rel (Glue (Tr r) s φ)) [] → ¬¬Acc (Rel (Glue (Tr r) s φ)) []) :
    ¬¬∃ img : PSet.{u}, ∀ y, y ∈ img ↔ ¬¬∃ x, x ∈ s ∧ φ x y := by
  subst hU
  have hT := fun η hη => hr.coherent (η := η) hη
  have hTr : ∀ {η η' p t}, η ≈ η' → Tr r η p t → Tr r η' p t := fun e h => tr_resp_root e h
  exact PSet.replacement (D := D) hT hTr φ_resp φ_func φ_C
    (hacc (swf_root (D := D) hT hTr φ_resp φ_func φ_C))

end Rule
